# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: spoolpra <marvin@42.fr>                    +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2022/01/29 12:28:05 by spoolpra          #+#    #+#              #
#    Updated: 2022/01/31 23:41:51 by spoolpra         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

CC = gcc
FLAG = -Wall -Werror -Wextra
SRCS = srcs/*.c
INCS = includes

all: compile

compile:
	$(CC) $(FLAG) -I $(INCS) $(SRCS) -o bsq

fclean:
	rm rush-02
